version: 2
updates:
  # Monitor your Node/pnpm dependencies
  - package-ecosystem: "npm"
    directory: "/"                # Root folder containing package.json
    schedule:
      interval: "daily"           # Run every day (use "weekly" if you prefer)
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    ignore:
      - dependency-name: "next"
        versions: ["*canary*"]

  # Keep GitHub Actions up-to-date too
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
