app = "mumu-whisper"
primary_region = "sjc"

[build]
  dockerfile = "containers/whisper/Dockerfile.gpu"
  build_context = "."   # build from backend directory

[env]
  NODE_ENV = "production"
  PORT = "8080"

[metrics]
  port = 8080
  path = "/metrics"

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 3
